

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: scp_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - scp_network

  nginx:
    image: nginx:latest
    container_name: scp_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - scp_network

  mysql:
    image: mysql:8
    container_name: scp_mysql
    restart: always
    environment:
      MYSQL_DATABASE: scp
      MYSQL_USER: scp_user
      MYSQL_PASSWORD: 100504
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - scp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: scp_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - scp_network

  redis:
    image: redis:latest
    container_name: scp_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - scp_network

networks:
  scp_network:

volumes:
  mysql_data:
