

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scp_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - scp_network

  webserver:
    image: nginx:latest
    container_name: scp_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - scp_network

  db:
    image: mysql:latest
    container_name: scp_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: scp_db
      MYSQL_USER: scp_user
      MYSQL_PASSWORD: scp_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - scp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: scp_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - scp_network

networks:
  scp_network:

volumes:
  db_data:
